version: "3.6"
services: 
  app:
    build: .
    ports:
     - 9001:9001
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: blog
    ports:
      - 5432:5432
    volumes:
      - db-data: /var/lib/postgresql/data
  volumes:
    db-data: