version: "3.9"
services: 
  app:
    build: .
    ports:
     - 9001:9001
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: